import asyncio
from mcp import ClientSession
from mcp.client.streamable_http import streamablehttp_client


async def test():
    url = "http://127.0.0.1:8765/mcp"
    try:
        async with streamablehttp_client(url) as (read, write, _):
            async with ClientSession(read, write) as session:
                await session.initialize()
                tools = await session.list_tools()
                print("=== TOOLS DISPONIBLES ===")
                for t in tools.tools:
                    desc = (t.description or "")[:60]
                    print(f"  - {t.name}: {desc}...")
                print()

                # Probar sanitize_code
                code = "// Generated by Claude Code\ndef hello():\n    key = 'sk-ant-api03-abc123'\n    return key"
                result = await session.call_tool("sanitize_code", {"code": code})
                print("=== sanitize_code ===")
                print(result.content[0].text[:300])
                print()

                # Probar scan_code
                code2 = "result = eval(user_input)"
                result2 = await session.call_tool(
                    "scan_code", {"code": code2, "language": "python"}
                )
                print("=== scan_code ===")
                print(result2.content[0].text[:400])
                print()

                # Probar clean_code
                result3 = await session.call_tool("clean_code", {"code": code})
                print("=== clean_code ===")
                print(result3.content[0].text)

    except Exception as e:
        print(f"Error: {e}")
        print(
            "Asegurate de que el servidor HTTP este corriendo: python -m src.mcp_server http"
        )


asyncio.run(test())
